### ISSUE TITLE
No `requirements.txt` file

### ISSUE THREAD

**Issue by seancannata** [mrahtz/ultra_ping#2]
Not sure if i'm missing something, usually there is a `requirements.txt` file so that anyone using the project can leverage pip to get all python packages needed:  `pip install -r requirements.txt`.

**Comment by mrahtz** [comment]
Which packages did you find you had to install? I think `logi` is the only exotic thing there and unfortunately it's not in pip.

**Comment by seancannata** [comment]
I had figured that logi was a python module. Good deal. Yeah, i'll close this. Thanks again! :+1:
