### ISSUE TITLE
No module named 'logi'

### ISSUE THREAD

**Issue by seancannata** [mrahtz/ultra_ping#3]
Where is this package available? I can't seem to find it anywhere. At the very least in my opinion needs to be in the README.md as to how to setup. This issue may be resolved with #1 

```
Traceback (most recent call last):
  File "./quack.py", line 23, in <module>
    import onewaymeasurement
  File "C:\tools\ultra_ping\onewaymeasurement.py", line 8, in <module>
    import logi_pi_timer
  File "C:\tools\ultra_ping\logi_pi_timer.py", line 6, in <module>
    import logi
ModuleNotFoundError: No module named 'logi'
```

**Comment by mrahtz** [comment]
Good catch, forgot to document that. It's from https://github.com/fpga-logi/logi-tools - but since it's something for the specific hardware platform we used, the LOGI Pi, I'm expecting most people to customise that part of the code. I've added a note to the README.

**Comment by seancannata** [comment]
Thanks! :+1:
