### ISSUE TITLE
import logi  

### ISSUE THREAD

**Issue by leechaowen** [mrahtz/ultra_ping#6]
HI, 

Could someone tell me how to install logi ? search the key word in the internet ,not find such packages.

 $python3 quack.py --server
Traceback (most recent call last):
  File "quack.py", line 23, in <module>
    import onewaymeasurement
  File "/home/lichaowen/ultra_ping/onewaymeasurement.py", line 8, in <module>
    import logi_pi_timer
  File "/home/lichaowen/ultra_ping/logi_pi_timer.py", line 6, in <module>
    import logi

$sudo pip install logi

ERROR: Could not find a version that satisfies the requirement logi (from versions: none)
ERROR: No matching distribution found for logi

**Comment by mrahtz** [comment]
For one-way latency measurement, you'll need both hosts to have access to a synchronised time source. We used a LOGI Pi FPGA, which we talked to using https://github.com/fpga-logi/logi-tools. Check the README section 'Latency Measurement' for more details.
