### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by pfandzelter** [mrahtz/ultra_ping#7]
Hi, thanks for the project, it was exactly what I was looking for.
I'm not sure if there is any ongoing maintenance here (as the package is perfect as it is) but I am missing a license for the code here, preferably an open-source one. It would be great if you could add one so that we can (legally) use and extend the project.
Thanks! 🙂

**Comment by mrahtz** [comment]
Glad it's helpful! I've set the license to MIT, so go ahead :)
