### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by snigel** [mrahtz/ultra_ping#8]
Tried to run ultra_ping using Python 3.10.

$ ./echo.py --client 192.168.0.1

`Sending 100 256-byte packets at about 400 kB/s to 192.168.0.1:8888...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/snigel/src/ultra_ping/measurement.py", line 46, in send_packets
    payload = bytes(payload + n_fill_bytes * fill_char)
TypeError: can't concat str to bytes
Note: timed out waiting to receive packets
So far, had received 0 packets
Received 0/100 packets back from server
`

If I understand correctly, the above can be solved by changing from
`payload = bytes(payload + n_fill_bytes * fill_char)`
to
`payload = bytes(payload + str.encode(n_fill_bytes * fill_char))`

After that has been done, a new error appears.
`Sending 100 256-byte packets at about 400 kB/s to 192.168.0.1:8888...
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/snigel/src/ultra_ping/roundtripmeasurement.py", line 103, in recv_packets
    payload = str.encode(packet).rstrip("a")
TypeError: descriptor 'encode' for 'str' objects doesn't apply to a 'bytes' object
Finished sending packets!
(Actually sent packets at 326 kB/s)`

The problem comes from this line:
`payload = packet.rstrip("a")`

It's not possible to rstrip on a bytes object and the object can't be decoded to a string since the first bytes won't decode as ascii or UTF-8.

**Comment by mrahtz** [comment]
Thanks for reporting! I probably won't have time to fix this any time soon, but I'd gladly accept a pull request.

**Comment by hydroid7** [comment]
See my pull request for python3.

**Comment by mrahtz** [comment]
Fixed with hydroid7's PR.
